module.exports = ['Adolfo Lucas Melo de Farias',
'Anderson Silva de Oliveira',
'Andreza Barbosa Rêgo',
'Andy Pereira de Castro Freitas',
'Antonio Falcao Bezerra Neto',
'Argus Halley da Rocha',
'Arthur Vinicius Marinho Rebelo',
'Bianca Cristiane Ferreira Santiago',
'Bruno Borges',
'Bruno Sielly Jales Costa',
'Caio Valério Catulo da Costa Oliveira',
'Caio Vitor Rodrigues da Costa Oliveira',
'Carlos Henrique Teixeira de Souza',
'Carolina Paiva Cavalcanti',
'Cláudio Henrique Bezerra de Souza',
'Daniel Freitas de Melo',
'Daniel Lucas de Melo Cunha',
'Danilo Oliveira Imparato',
'Davi Carvalho Feitosa Gonçalves',
'Davidson Fellipe da Silva',
'Dayane Pabla de Araújo Vilaça',
'Diego de Oliveira Toral',
'Diego Soares dos Santos',
'Éricles de Lima Freitas',
'Esther Aragão da Silva Santana',
'Ewerton do Nascimento Gomes da Silva',
'Gabriel Bezerra Venâncio Magalhães Oest',
'Guilherme José Souza Barros',
'Igor de Medeiros',
'Ionaldo Carvalho Júnior',
'Ítalo Berg Marques Souza dos Reis',
'Jaimerson Leandro Amaro de Araújo',
'Jefferson Augusto Rodrigues de Azevedo',
'Jonas Elan Teixeira Alves',
'Jonatas Oliveira',
'Jorge Augusto da Costa Dantas',
'Josafá Romão Rebouças Rodrigues',
'José Paulo Alves Policarpo',
'Julian Ignacio Sansat',
'Juliano Cardoso',
'Jurandy Martins Soares Junior',
'Karlisson Rolim do Santos ',
'Katyanna Moura',
'Kellyson Victor Santos',
'Késsia Castro',
'Leonardo Nascimento de Oliveira',
'Lucilvan Freitas Silva',
'Luiz Antonio Ferreira Júnior',
'Luiz Cláudio Lopes Rocha',
'Márcio Araújo',
'Maria Júlia Martins Silva',
'Mário Idival',
'Mateus Pinheiro de Lima',
'Matheus Joan Miranda de Oliveira',
'Micael de Souza Xavier Lima',
'Otávio Bruno Leite Barbosa',
'Ottony Chamberlaine Tavares da Costa',
'Ozifrankly Lima da Silva',
'Missilene Farias',
'Paulo Alexandre Ananias da Costa',
'Rafael Holanda de Lima',
'Raphael Costa Avelino',
'Raphael Mendonça da Nóbrega',
'Renato Barbalho Lavôr',
'Renato Freire Soares de Lima',
'Rodolfo Araújo',
'Rodrigo Nascimento de Sousa',
'Rômulo Bosco da Silva',
'Thales Medeiros ',
'Thiago Ismael',
'Vinícius Brandão Mendes',
'Wanderley Passos',
'Wilde Bezerra Alencar de Carvalho',
'Yuri Henrique Sales da Costa'];
